# Generated by Django 6.0.4 on 2026-04-29 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_id", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "db_table": "weather_station",
            },
        ),
        migrations.CreateModel(
            name="WeatherObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("max_temp", models.FloatField(null=True)),
                ("min_temp", models.FloatField(null=True)),
                ("precipitation", models.FloatField(null=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="weather.weatherstation",
                    ),
                ),
            ],
            options={
                "db_table": "weather_observation",
                "indexes": [
                    models.Index(fields=["date"], name="weather_obs_date_ee26c0_idx"),
                    models.Index(
                        fields=["station", "date"],
                        name="weather_obs_station_8a617d_idx",
                    ),
                ],
                "unique_together": {("station", "date")},
            },
        ),
        migrations.CreateModel(
            name="WeatherStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("avg_max_temp", models.FloatField(null=True)),
                ("avg_min_temp", models.FloatField(null=True)),
                ("total_precipitation", models.FloatField(null=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="weather.weatherstation",
                    ),
                ),
            ],
            options={
                "db_table": "weather_stats",
                "indexes": [
                    models.Index(fields=["year"], name="weather_sta_year_4e0893_idx"),
                    models.Index(
                        fields=["station", "year"],
                        name="weather_sta_station_9ced86_idx",
                    ),
                ],
                "unique_together": {("station", "year")},
            },
        ),
    ]
