# Generated by Django 6.0.4 on 2026-04-30 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherstats',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='weatherstats',
            name='weather_sta_year_4e0893_idx',
        ),
        migrations.RemoveIndex(
            model_name='weatherstats',
            name='weather_sta_station_9ced86_idx',
        ),
        migrations.DeleteModel(
            name='WeatherStats',
        ),
    ]
