# Generated by Django 6.0.4 on 2026-04-30 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weatherstats_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('avg_max_temp', models.FloatField(null=True)),
                ('avg_min_temp', models.FloatField(null=True)),
                ('total_precipitation', models.FloatField(null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='weather.weatherstation')),
            ],
            options={
                'db_table': 'weather_stats',
                'indexes': [models.Index(fields=['year'], name='weather_sta_year_4e0893_idx'), models.Index(fields=['station', 'year'], name='weather_sta_station_9ced86_idx')],
                'unique_together': {('station', 'year')},
            },
        ),
    ]
